[common]
server_addr = "{{ .Envs.FRP_SERVER_ADDR }}"
server_port = 7000
token = "{{ .Envs.FRP_TOKEN }}"

[[proxy-{{ .Envs.FRP_REMOTE_PORT }}]]
type = "tcp"
remote_port = "{{ .Envs.FRP_REMOTE_PORT }}"
local_ip = "127.0.0.1"
local_port = 3128
